import type { Metadata } from "next";
import { Bebas_Neue, Space_Mono } from "next/font/google";
import "./globals.css";

const bebasNeue = Bebas_Neue({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-bebas-neue",
  display: "swap",
});

const spaceMono = Space_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-space-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Backfield Ventures | Venture Capital for Sports and Consumer Brands",
  description:
    "Backfield Ventures backs the next generation of consumer and sports companies. Seed to Series A. If you're a founder, investor, or operator — let's talk.",
  applicationName: "Backfield Ventures",
  metadataBase: new URL("https://backfieldventures.com"),
  alternates: {
    canonical: "https://backfieldventures.com",
  },
  keywords: [
    "venture capital",
    "consumer brands",
    "sports venture capital",
    "seed funding",
    "Series A",
    "DTC startups",
    "consumer health wellness",
    "sports technology investment",
    "fan engagement",
    "athlete brands",
    "sports media streaming",
    "sports data analytics",
    "early stage venture",
    "consumer product startup funding",
    "sports company investment",
    "venture capital fund",
    "venture capital for consumer brands",
    "community platforms",
    "lifestyle brands",
    "commerce marketplaces",
    "pre-seed investment",
    "Backfield Ventures",
  ],
  openGraph: {
    title: "Backfield Ventures | Venture Capital for Sports and Consumer Brands",
    description:
      "Backfield Ventures backs the next generation of consumer and sports companies. Seed to Series A. If you're a founder, investor, or operator — let's talk.",
    url: "https://backfieldventures.com",
    siteName: "Backfield Ventures",
    type: "website",
    locale: "en_US",
    // og:image is auto-generated from src/app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Backfield Ventures | Venture Capital for Sports and Consumer Brands",
    description:
      "Backfield Ventures backs the next generation of consumer and sports companies. Seed to Series A. If you're a founder, investor, or operator — let's talk.",
    // twitter:image falls back to og:image (generated by opengraph-image.tsx)
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  },
  icons: {
    icon: [
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
    ],
    apple: "/apple-touch-icon.png",
    other: [{ rel: "manifest", url: "/site.webmanifest" }],
  },
};

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      name: "Backfield Ventures",
      url: "https://backfieldventures.com",
      logo: "https://backfieldventures.com/logo-text.png",
      description:
        "Backfield Ventures is a venture capital firm investing in consumer brands and sports companies from pre-seed through Series A.",
      email: "hello@backfieldventures.com",
      sameAs: ["https://www.linkedin.com/company/backfield-ventures"],
    },
    {
      "@type": "FAQPage",
      mainEntity: [
        {
          "@type": "Question",
          name: "What does Backfield Ventures invest in?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Backfield Ventures invests in consumer brands and sports companies. Our consumer focus includes DTC brands, consumer health & wellness, community-driven platforms, modern lifestyle brands, and commerce & marketplaces. Our sports focus includes fan engagement & experiences, athlete brands & ventures, sports technology, media & streaming, and sports data & analytics.",
          },
        },
        {
          "@type": "Question",
          name: "How do I get funding from Backfield Ventures?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Reach out directly at hello@backfieldventures.com with the subject 'Founder Intro'. We read every deck and respond to every serious inquiry.",
          },
        },
        {
          "@type": "Question",
          name: "What stage does Backfield Ventures invest at?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Our primary focus is Seed and Series A. We invest selectively at Pre-Seed when the opportunity is compelling, and occasionally at Series B+ when we have meaningful insight into the business.",
          },
        },
        {
          "@type": "Question",
          name: "How can investors or LPs learn about Backfield Ventures?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "We're selective about LP relationships. Reach out at hello@backfieldventures.com with the subject 'LP Inquiry' to learn more about our focus and portfolio.",
          },
        },
        {
          "@type": "Question",
          name: "How can operators or partners work with Backfield Ventures?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "If you work in consumer or sports and want to explore collaboration — for portfolio companies or in a broader capacity — reach out at hello@backfieldventures.com with the subject 'Partnership'.",
          },
        },
      ],
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${bebasNeue.variable} ${spaceMono.variable}`}>
      <head>
        <link rel="preconnect" href="https://api.fontshare.com" />
        <link
          href="https://api.fontshare.com/v2/css?f[]=switzer@300,400,500,700&display=swap"
          rel="stylesheet"
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className="grain">{children}</body>
    </html>
  );
}
